


export const metadata = {
  title: 'Blog list',
  description: 'Generated by HOI DAN IT',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
        {children}
    </>
  )
}
